services:
  - type: web
    name: reelranker-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://reel-ranker.onrender.com
      - key: REACT_APP_ENVIRONMENT
        value: production
      - key: NODE_ENV
        value: production
      - key: GENERATE_SOURCEMAP
        value: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
