version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: reelranker-postgres
    environment:
      POSTGRES_DB: reelranker
      POSTGRES_USER: reelranker
      POSTGRES_PASSWORD: reelranker123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: reelranker-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
